source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLUX_Example' do
  pod "FLUX", :path => "../"

  target 'FLUX_Tests' do
    pod "FLUX", :path => "../"
    pod 'Kiwi'
    pod 'OCMock'
    pod 'Expecta'
  end
end
