source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FLUX_Example', :exclusive => true do
  pod "FLUX", :path => "../"
end

target 'FLUX_Tests', :exclusive => true do
  pod "FLUX", :path => "../"

  pod 'Kiwi'
end
