fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  desc "Runs the unit tests"
  lane :test do
    cocoapods
    scan
    if is_ci?
      slather
    end
    pod_lib_lint
  end

  desc "Generates documentation for a framework"
  lane :gen_docs do
    # temporary workaround when using SPM dir format
    # https://github.com/realm/jazzy/issues/667
    sh("mv ../Sources ../FLUX")
    jazzy
    sh("mv ../FLUX ../Sources")
  end
end
